# BT3017 Tutorial 6

- There is an online copy<sup>+</sup> of this tutorial on github available [here](https://github.com/KohSiXing/Feature-Engineering-for-Machine-Learning/blob/master/BT3017%20Tutorial%206.ipynb)

<sup>+</sup> Online copy will only be published after Wednesday 1000 of that week to prevent plagiarism.

### Preprocessing

- Same as in tutorial 5, graph will be built in this format 
    - Node A will be tag to index 0, Node B tag to index 1 and so on till Node L tag to index 11
    - a<sub>ij</sub> will be 0 when *$i = j$*

In [1]:
import numpy as np
import pandas as pd
from functools import reduce

# Dictionary Data for easy conversion
nodesChart = {'A':0, 'B':1, 'C':2, 'D':3, 'E':4, 'F':5, 'G':6, 'H':7, 'I':8, 'J':9, 'K':10, 'L':11}
nodesChart

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11}

### a

- Build Adjacency Matrix $A$ (12 by 12)
- Graph is an unweighted and undirected graph, a<sub>ij</sub> are set to 1 if there is a connection and 0 otherwise (where *$i \ne j$*)
- If a<sub>ij</sub> exists, then a<sub>ji</sub> exists and are identical

In [2]:
# Construct the adjacency matrix
A = np.zeros((12,12))

connectedPairs = (('A','B'), ('A','C'), ('A', 'D'), ('A', 'E'), ('B', 'F'), ('C', 'G'), ('D', 'H'), ('E', 'I'), 
                  ('G','J'), ('H','K'), ('I','L'))

for i in connectedPairs:
    A[nodesChart[i[0]]][nodesChart[i[1]]] = 1
    A[nodesChart[i[1]]][nodesChart[i[0]]] = 1
    
A

array([[0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

### b

- Compute degree matrix $D$ where degree of each node are stored in the leading diagonals

In [3]:
D = np.zeros((12,12))

for i in range(len(D)):
    deg = reduce(lambda x,y : x + y, A[i])
    D[i][i] = deg
D

array([[4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### c

- Compute *Graph Laplacian*

$L = D - A$

In [4]:
## Using Lap as the variable to store Graph Laplacian since variable L will be used later
Lap = D - A
pd.DataFrame(Lap)

0    1    2    3    4    5    6    7    8    9    10   11
0   4.0 -1.0 -1.0 -1.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  -1.0  2.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0  0.0  0.0  0.0
2  -1.0  0.0  2.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0  0.0  0.0
3  -1.0  0.0  0.0  2.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0  0.0
4  -1.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0
5   0.0 -1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0 -1.0  0.0  0.0  0.0  2.0  0.0  0.0 -1.0  0.0  0.0
7   0.0  0.0  0.0 -1.0  0.0  0.0  0.0  2.0  0.0  0.0 -1.0  0.0
8   0.0  0.0  0.0  0.0 -1.0  0.0  0.0  0.0  2.0  0.0  0.0 -1.0
9   0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  1.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  1.0  0.0
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -1.0  0.0  0.0  1.0

### d

- Get the eigenvalues and eigenvectors, store them in *w* and *v* respectively

In [5]:
w,v = np.linalg.eig(Lap)
w

array([ 5.32340428e+00, -5.66400587e-16,  3.18669356e-01,  1.00000000e+00,
        2.35792637e+00,  3.00000000e+00,  3.24697960e+00,  1.55495813e+00,
        1.98062264e-01,  1.98062264e-01,  1.55495813e+00,  3.24697960e+00])

- Sort the eigenvalues and eigenvectors

In [6]:
idx = np.argsort(w)
w = w[idx]
v = v[:,idx]

- Create the diagonal matrix $\Lambda$ with eigenvalues as its diagonals. Based on the results, we know that there will only be one cluster and indeed all the nodes form a single connected component in the graph

In [7]:
lmbd = np.zeros((12,12))

for i in range(len(lmbd)):
    lmbd[i][i] = w[i]
    
pd.DataFrame(lmbd).round(decimals = 5)

0        1        2        3    4        5        6        7    8   \
0  -0.0  0.00000  0.00000  0.00000  0.0  0.00000  0.00000  0.00000  0.0   
1   0.0  0.19806  0.00000  0.00000  0.0  0.00000  0.00000  0.00000  0.0   
2   0.0  0.00000  0.19806  0.00000  0.0  0.00000  0.00000  0.00000  0.0   
3   0.0  0.00000  0.00000  0.31867  0.0  0.00000  0.00000  0.00000  0.0   
4   0.0  0.00000  0.00000  0.00000  1.0  0.00000  0.00000  0.00000  0.0   
5   0.0  0.00000  0.00000  0.00000  0.0  1.55496  0.00000  0.00000  0.0   
6   0.0  0.00000  0.00000  0.00000  0.0  0.00000  1.55496  0.00000  0.0   
7   0.0  0.00000  0.00000  0.00000  0.0  0.00000  0.00000  2.35793  0.0   
8   0.0  0.00000  0.00000  0.00000  0.0  0.00000  0.00000  0.00000  3.0   
9   0.0  0.00000  0.00000  0.00000  0.0  0.00000  0.00000  0.00000  0.0   
10  0.0  0.00000  0.00000  0.00000  0.0  0.00000  0.00000  0.00000  0.0   
11  0.0  0.00000  0.00000  0.00000  0.0  0.00000  0.00000  0.00000  0.0   

         9        10      11  
0   0.00000  0.00000  0.0000  
1   0.00000  0.00000  0.0000  
2   0.00000  0.00000  0.0000  
3   0.00000  0.00000  0.0000  
4   0.00000  0.00000  0.0000  
5   0.00000  0.00000  0.0000  
6   0.00000  0.00000  0.0000  
7   0.00000  0.00000  0.0000  
8   0.00000  0.00000  0.0000  
9   3.24698  0.00000  0.0000  
10  0.00000  3.24698  0.0000  
11  0.00000  0.00000  5.3234

#### i) Compute $L * x$, where $L = V \Lambda V^{T}$

$L * x = V \Lambda V^{T} * x$

- Create `x` as a column vector

In [8]:
x = np.array([1,0,0,0,0,0,0,0,0,0,0,0])
x = x.T
pd.DataFrame(x, columns = ["x"])

x
0   1
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   0
10  0
11  0

- Codes below are just **meant for checking** against the matrix above for $L = D - A$. They are the same, and $L = V \Lambda V^{T}$ holds true

In [9]:
L = v @ lmbd @ v.T
pd.DataFrame(L).round(decimals = 0)

0    1    2    3    4    5    6    7    8    9    10   11
0   4.0 -1.0 -1.0 -1.0 -1.0  0.0 -0.0 -0.0  0.0  0.0  0.0  0.0
1  -1.0  2.0 -0.0 -0.0  0.0 -1.0 -0.0 -0.0 -0.0  0.0  0.0  0.0
2  -1.0 -0.0  2.0  0.0 -0.0 -0.0 -1.0  0.0 -0.0 -0.0 -0.0  0.0
3  -1.0 -0.0  0.0  2.0  0.0 -0.0  0.0 -1.0 -0.0 -0.0  0.0 -0.0
4  -1.0  0.0 -0.0  0.0  2.0 -0.0 -0.0 -0.0 -1.0  0.0 -0.0 -0.0
5   0.0 -1.0 -0.0 -0.0 -0.0  1.0  0.0  0.0  0.0 -0.0 -0.0 -0.0
6  -0.0 -0.0 -1.0  0.0 -0.0  0.0  2.0  0.0 -0.0 -1.0 -0.0  0.0
7  -0.0 -0.0  0.0 -1.0 -0.0  0.0  0.0  2.0  0.0 -0.0 -1.0 -0.0
8   0.0 -0.0 -0.0 -0.0 -1.0  0.0 -0.0  0.0  2.0  0.0 -0.0 -1.0
9   0.0  0.0 -0.0 -0.0  0.0 -0.0 -1.0 -0.0  0.0  1.0  0.0 -0.0
10  0.0  0.0 -0.0  0.0 -0.0 -0.0 -0.0 -1.0 -0.0  0.0  1.0 -0.0
11  0.0  0.0  0.0 -0.0 -0.0 -0.0  0.0 -0.0 -1.0 -0.0 -0.0  1.0

- From the results below, we are able to detemine nodes that are only 1 steps away from `Node A` (i.e. index 0). We can determine based on the non-zero values:
    - 1 step away `[B, C, D, E]` correspond to indices [1, 2, 3, 4]

In [10]:
pd.DataFrame(Lap @ x, columns = ["L * x"]).round(decimals = 0)

L * x
0     4.0
1    -1.0
2    -1.0
3    -1.0
4    -1.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0

#### ii) compute $L * L * x$

$L * L * x = V \Lambda V^{T} V \Lambda V^{T} * x$ 

- since $V^{T} V = I$, therefore $L * L * x = V \Lambda^{2} V^{T} * x$

In [11]:
Lap2 = Lap @ Lap
pd.DataFrame(Lap2).round(decimals = 0)

0    1    2    3    4    5    6    7    8    9    10   11
0   20.0 -6.0 -6.0 -6.0 -6.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0
1   -6.0  6.0  1.0  1.0  1.0 -3.0  0.0  0.0  0.0  0.0  0.0  0.0
2   -6.0  1.0  6.0  1.0  1.0  0.0 -4.0  0.0  0.0  1.0  0.0  0.0
3   -6.0  1.0  1.0  6.0  1.0  0.0  0.0 -4.0  0.0  0.0  1.0  0.0
4   -6.0  1.0  1.0  1.0  6.0  0.0  0.0  0.0 -4.0  0.0  0.0  1.0
5    1.0 -3.0  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0
6    1.0  0.0 -4.0  0.0  0.0  0.0  6.0  0.0  0.0 -3.0  0.0  0.0
7    1.0  0.0  0.0 -4.0  0.0  0.0  0.0  6.0  0.0  0.0 -3.0  0.0
8    1.0  0.0  0.0  0.0 -4.0  0.0  0.0  0.0  6.0  0.0  0.0 -3.0
9    0.0  0.0  1.0  0.0  0.0  0.0 -3.0  0.0  0.0  2.0  0.0  0.0
10   0.0  0.0  0.0  1.0  0.0  0.0  0.0 -3.0  0.0  0.0  2.0  0.0
11   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 -3.0  0.0  0.0  2.0

- Codes below are just **meant for checking** against the matrix above. They are the same, and $L * L = V \Lambda^{2} V^{T}$ holds true

In [12]:
L2 = v @ lmbd @ lmbd @ v.T
pd.DataFrame(L2).round(decimals = 0)

0    1    2    3    4    5    6    7    8    9    10   11
0   20.0 -6.0 -6.0 -6.0 -6.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0
1   -6.0  6.0  1.0  1.0  1.0 -3.0 -0.0 -0.0 -0.0  0.0  0.0  0.0
2   -6.0  1.0  6.0  1.0  1.0 -0.0 -4.0  0.0 -0.0  1.0 -0.0  0.0
3   -6.0  1.0  1.0  6.0  1.0 -0.0  0.0 -4.0 -0.0 -0.0  1.0  0.0
4   -6.0  1.0  1.0  1.0  6.0 -0.0 -0.0 -0.0 -4.0  0.0  0.0  1.0
5    1.0 -3.0 -0.0 -0.0 -0.0  2.0  0.0  0.0  0.0 -0.0 -0.0 -0.0
6    1.0 -0.0 -4.0  0.0 -0.0  0.0  6.0 -0.0 -0.0 -3.0 -0.0  0.0
7    1.0 -0.0  0.0 -4.0 -0.0  0.0 -0.0  6.0  0.0 -0.0 -3.0 -0.0
8    1.0 -0.0 -0.0 -0.0 -4.0  0.0 -0.0  0.0  6.0  0.0 -0.0 -3.0
9    0.0  0.0  1.0 -0.0  0.0 -0.0 -3.0 -0.0  0.0  2.0  0.0 -0.0
10   0.0  0.0 -0.0  1.0  0.0 -0.0 -0.0 -3.0 -0.0  0.0  2.0  0.0
11   0.0  0.0  0.0  0.0  1.0 -0.0  0.0 -0.0 -3.0 -0.0  0.0  2.0

- From the results below, we are able to detemine nodes that are up to 2 steps away from `Node A` (i.e. index 0). We can determine which group the nodes belongs to from the non-zero values that are the same:
    - 1 step away `[B, C, D, E]` correspond to indices [1, 2, 3, 4]
    - 2 step away `[F, G, H, I]` correspond to indices [5, 6, 7, 8]

In [13]:
pd.DataFrame(Lap2 @ x, columns = ["L * L * x"]).round(decimals = 0)

L * L * x
0        20.0
1        -6.0
2        -6.0
3        -6.0
4        -6.0
5         1.0
6         1.0
7         1.0
8         1.0
9         0.0
10        0.0
11        0.0

#### ii) compute $L * L * L * x$

In [14]:
Lap3 = Lap @ Lap @ Lap
pd.DataFrame(Lap3).round(decimals = 0)

0     1     2     3     4    5     6     7     8    9    10   11
0   104.0 -33.0 -33.0 -33.0 -33.0  7.0   8.0   8.0   8.0 -1.0 -1.0 -1.0
1   -33.0  21.0   8.0   8.0   8.0 -9.0  -1.0  -1.0  -1.0  0.0  0.0  0.0
2   -33.0   8.0  22.0   8.0   8.0 -1.0 -15.0  -1.0  -1.0  5.0  0.0  0.0
3   -33.0   8.0   8.0  22.0   8.0 -1.0  -1.0 -15.0  -1.0  0.0  5.0  0.0
4   -33.0   8.0   8.0   8.0  22.0 -1.0  -1.0  -1.0 -15.0  0.0  0.0  5.0
5     7.0  -9.0  -1.0  -1.0  -1.0  5.0   0.0   0.0   0.0  0.0  0.0  0.0
6     8.0  -1.0 -15.0  -1.0  -1.0  0.0  19.0   0.0   0.0 -9.0  0.0  0.0
7     8.0  -1.0  -1.0 -15.0  -1.0  0.0   0.0  19.0   0.0  0.0 -9.0  0.0
8     8.0  -1.0  -1.0  -1.0 -15.0  0.0   0.0   0.0  19.0  0.0  0.0 -9.0
9    -1.0   0.0   5.0   0.0   0.0  0.0  -9.0   0.0   0.0  5.0  0.0  0.0
10   -1.0   0.0   0.0   5.0   0.0  0.0   0.0  -9.0   0.0  0.0  5.0  0.0
11   -1.0   0.0   0.0   0.0   5.0  0.0   0.0   0.0  -9.0  0.0  0.0  5.0

- Codes below are just **meant for checking** against the matrix above. They are the same, and $L * L * L = V \Lambda^{3} V^{T}$ holds true

In [15]:
L3 = v @ lmbd @ lmbd @ lmbd @ v.T
pd.DataFrame(L3).round(decimals = 0)

0     1     2     3     4    5     6     7     8    9    10   11
0   104.0 -33.0 -33.0 -33.0 -33.0  7.0   8.0   8.0   8.0 -1.0 -1.0 -1.0
1   -33.0  21.0   8.0   8.0   8.0 -9.0  -1.0  -1.0  -1.0  0.0  0.0  0.0
2   -33.0   8.0  22.0   8.0   8.0 -1.0 -15.0  -1.0  -1.0  5.0 -0.0  0.0
3   -33.0   8.0   8.0  22.0   8.0 -1.0  -1.0 -15.0  -1.0 -0.0  5.0  0.0
4   -33.0   8.0   8.0   8.0  22.0 -1.0  -1.0  -1.0 -15.0  0.0  0.0  5.0
5     7.0  -9.0  -1.0  -1.0  -1.0  5.0   0.0   0.0   0.0 -0.0 -0.0 -0.0
6     8.0  -1.0 -15.0  -1.0  -1.0  0.0  19.0  -0.0   0.0 -9.0 -0.0  0.0
7     8.0  -1.0  -1.0 -15.0  -1.0  0.0  -0.0  19.0   0.0 -0.0 -9.0 -0.0
8     8.0  -1.0  -1.0  -1.0 -15.0  0.0   0.0   0.0  19.0  0.0 -0.0 -9.0
9    -1.0   0.0   5.0  -0.0   0.0 -0.0  -9.0  -0.0   0.0  5.0  0.0 -0.0
10   -1.0   0.0  -0.0   5.0   0.0 -0.0  -0.0  -9.0  -0.0  0.0  5.0  0.0
11   -1.0   0.0   0.0   0.0   5.0 -0.0   0.0  -0.0  -9.0 -0.0  0.0  5.0

- From the results below, we are able to detemine nodes that are 3 steps away from `Node A` (i.e. index 0). We can determine which group the nodes belongs to from the non-zero values that are the same:
    - 1 step away `[B, C, D, E]` correspond to indices [1, 2, 3, 4]
    - 2 step away `[F, G, H, I]` correspond to indices [5, 6, 7, 8] (there may be some rounding off errors for F, but the values are all close to 8)
    - 3 step away `[J, K, L]` correspond to indices [9, 10, 11]

In [16]:
pd.DataFrame(Lap3 @ x , columns = ["L * L * L * x"]).round(decimals = 0)

L * L * L * x
0           104.0
1           -33.0
2           -33.0
3           -33.0
4           -33.0
5             7.0
6             8.0
7             8.0
8             8.0
9            -1.0
10           -1.0
11           -1.0