In [1]:
import pandas as pd
import numpy as np

M = [[4, -3, 0],
     [2, -1, 2],
     [1, 5, 7]]

M

[[4, -3, 0], [2, -1, 2], [1, 5, 7]]

In [2]:
w,v = np.linalg.eig(M)
w

array([ 7.81129276,  3.39527581, -1.20656856])

In [3]:
v

array([[ 0.14722557, -0.86037799, -0.43022492],
       [-0.18703991, -0.17343046, -0.74666518],
       [-0.97125728,  0.47924063,  0.5073437 ]])

In [4]:
np.argsort(-1 * w)

array([0, 1, 2], dtype=int64)

In [5]:
L = np.zeros((3,3))

for i in range(len(w)):
    L[i][i] = w[i]
    
L

array([[ 7.81129276,  0.        ,  0.        ],
       [ 0.        ,  3.39527581,  0.        ],
       [ 0.        ,  0.        , -1.20656856]])

In [6]:
np.dot(v,L)

array([[ 1.15002201, -2.92122058,  0.51909586],
       [-1.46102351, -0.58884425,  0.90090273],
       [-7.58677495,  1.62715413, -0.61214495]])

### First Column [:, 1]

In [7]:
(0.14722557 * 7.81129276)

1.150022029027873

In [8]:
(-0.18703991 * 7.81129276)

-1.4610234948140515

In [9]:
(-0.97125728 * 7.81129276)

-7.586774959361293

### Second Column [:, 2]

In [10]:
-0.86037799 * 3.39527581

-2.921220576903422

In [11]:
-0.17343046 * 3.39527581

-0.5888442455551726

In [12]:
0.47924063 * 3.39527581

1.6271541182081601

### Third Column [:, 3]

In [13]:
-0.43022492 * -1.20656856

0.5190958622005152

In [14]:
-0.74666518 * -1.20656856

0.9009027310347408

In [15]:
0.5073437 * -1.20656856

-0.6121449575340719